spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: food-api-service

server:
  port: ${PORT:8081}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} ${spring.application.name} %-5level [%thread] %logger{36} traceId=%X{traceId} spanId=%X{spanId} - %msg%n"
    file:    "%d{yyyy-MM-dd HH:mm:ss.SSS} ${spring.application.name} %-5level [%thread] %logger{36} traceId=%X{traceId} spanId=%X{spanId} - %msg%n"
