spring:
  datasource:
    url: jdbc:h2:file:D:\Personal Project\h2-db\food-service\food.db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

mail:
  host: smtp.gmail.com
  port: 587
  username: nhameyorder@gmail.com
  password: cozzogfbudpmfnss
  default-encoding: UTF-8
  debug: false

  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

web:
  portal:
    url: "http://localhost:5173"