spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect




mail:
  host: smtp.gmail.com
  port: 587
  username: ${GMAIL_USERNAME:}
  password: ${GMAIL_APPPASSWORD:}
  default-encoding: UTF-8
  debug: false

  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

web:
  portal:
    url: "https://food-order-wing.vercel.app"