spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${DB_USER:}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect




mail:
  host: smtp.gmail.com
  port: 587
  username: yourgmail@gmail.com          # your full Gmail address
  password: your_app_password_here       # 16-char app password (NOT your normal pw)
  default-encoding: UTF-8
  debug: false

  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true