spring:
  datasource:
    url: jdbc:h2:file:D:\Personal Project\h2-db\food-service\food.db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

mail:
  host: smtp.gmail.com
  port: 587
  username: yourgmail@gmail.com          # your full Gmail address
  password: your_app_password_here       # 16-char app password (NOT your normal pw)
  default-encoding: UTF-8
  debug: false

  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true

